
package com.ifugle.test.webservice.base;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Gt3AipWebService", targetNamespace = "http://www.chinatax.gov.cn/spec/", wsdlLocation = "http://150.12.56.135:8001/gt3aipservice?wsdl")
public class Gt3AipWebService_Service
    extends Service
{

    private final static URL GT3AIPWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException GT3AIPWEBSERVICE_EXCEPTION;
    private final static QName GT3AIPWEBSERVICE_QNAME = new QName("http://www.chinatax.gov.cn/spec/", "Gt3AipWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://150.12.56.135:8001/gt3aipservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GT3AIPWEBSERVICE_WSDL_LOCATION = url;
        GT3AIPWEBSERVICE_EXCEPTION = e;
    }

    public Gt3AipWebService_Service() {
        super(__getWsdlLocation(), GT3AIPWEBSERVICE_QNAME);
    }

    public Gt3AipWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GT3AIPWEBSERVICE_QNAME, features);
    }

    public Gt3AipWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, GT3AIPWEBSERVICE_QNAME);
    }

    public Gt3AipWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GT3AIPWEBSERVICE_QNAME, features);
    }

    public Gt3AipWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Gt3AipWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Gt3AipWebService
     */
    @WebEndpoint(name = "Gt3AipWebServiceSoapPort")
    public Gt3AipWebService getGt3AipWebServiceSoapPort() {
        return super.getPort(new QName("http://www.chinatax.gov.cn/spec/", "Gt3AipWebServiceSoapPort"), Gt3AipWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Gt3AipWebService
     */
    @WebEndpoint(name = "Gt3AipWebServiceSoapPort")
    public Gt3AipWebService getGt3AipWebServiceSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.chinatax.gov.cn/spec/", "Gt3AipWebServiceSoapPort"), Gt3AipWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GT3AIPWEBSERVICE_EXCEPTION!= null) {
            throw GT3AIPWEBSERVICE_EXCEPTION;
        }
        return GT3AIPWEBSERVICE_WSDL_LOCATION;
    }

}
