
package com.ifugle.test.webservice.base;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Gt3AipWebService", targetNamespace = "http://www.chinatax.gov.cn/spec/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Gt3AipWebService {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "service", targetNamespace = "http://www.chinatax.gov.cn/spec/", partName = "response")
    public String sendBaseXMLEsbWebService(
        @WebParam(name = "service", targetNamespace = "http://www.chinatax.gov.cn/spec/", partName = "request")
        String request);

}
